Seguros.Falabella.Application/Controllers/SaleController.cs
using Seguros.Falabella.Application.Models;
using Seguros.Falabella.Application.ServiceSale;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Seguros.Falabella.Application.Controllers
{
    public class SaleController : Controller
    {
        private readonly SaleWCFClient SalClient = new SaleWCFClient();

        // GET: Sale
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult SelectCustomer()
        {
            List<Customer> model;
            try
            {
                model = SalClient.SelectCustomer().ToList();
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message, ex.InnerException);
            }
            return View(model);
        }

        public ActionResult SelectSale()
        {
            List<Sale> model;
            try
            {
                model = SalClient.SelectSale().ToList();
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message, ex.InnerException);
            }
            return View(model);
        }

        public ActionResult SelectSaleId(int id)
        {
            Sale model = new Sale();
            try
            {
                model = SalClient.SelectSaleId(id);
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message, ex.InnerException);
            }
            return View(model);
        }

        public ActionResult CreateSale()
        {
            return View();
        }

        public ActionResult AddSale(Sale Obejto)
        {
            try
            {
                SalClient.AddSale(Obejto);
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message, ex.InnerException);
            }
            return RedirectToAction("Index");
        }

        public ActionResult CreateSaleCustomer()
        {
            return View();
        }

        public ActionResult AddSaleCustomer(Sale Obejto)
        {
            try
            {
                SalClient.AddSaleCustomer(Obejto);
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message, ex.InnerException);
            }
            return RedirectToAction("Index");
        }


    }
}

Seguros.Falabella.Application/Views/Sale/CreateSale.cshtml
@model Seguros.Falabella.Application.ServiceSale.Sale

@{
    ViewBag.Title = "CreateSale";
}

<h2>CreateSale</h2>

@using (Html.BeginForm("AddSale", "Sale", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Sale</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.cust_id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.cust_id, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.cust_id, "", new { @class = "text-danger" })
            </div>
        </div> 

        <div class="form-group">
            @Html.LabelFor(model => model.prod_id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.prod_id, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.prod_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.sale_assistance, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.sale_assistance, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.sale_assistance, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.sale_coverage, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.sale_coverage, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.sale_coverage, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.sale_prima, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.sale_prima, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.sale_prima, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Seguros.Falabella.Application/Views/Sale/CreateSaleCustomer.cshtml
@model Seguros.Falabella.Application.ServiceSale.Sale

@{
    ViewBag.Title = "CreateSaleCustomer";
}

<h2>CreateSaleCustomer</h2>

@using (Html.BeginForm("AddSaleCustomer", "Sale", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Sale</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        

        <div class="form-group">
            @Html.LabelFor(model => model.cust_cc, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.cust_cc, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.cust_cc, "", new { @class = "text-danger" })
            </div>
        </div>        

        <div class="form-group">
            @Html.LabelFor(model => model.cust_lastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.cust_lastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.cust_lastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.cust_name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.cust_name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.cust_name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.cust_city, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.cust_city, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.cust_city, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.cust_dateOfBirth, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.cust_dateOfBirth, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.cust_dateOfBirth, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.cust_address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.cust_address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.cust_address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.cust_phone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.cust_phone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.cust_phone, "", new { @class = "text-danger" })
            </div>
        </div>        

        <div class="form-group">
            @Html.LabelFor(model => model.prod_id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.prod_id, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.prod_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.sale_assistance, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.sale_assistance, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.sale_assistance, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.sale_coverage, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.sale_coverage, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.sale_coverage, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.sale_prima, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.sale_prima, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.sale_prima, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Seguros.Falabella.Application/Views/Sale/Index.cshtml

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<div class="container">
    <div class="col-md-6 text-center">
        <p class="lead">Lista de clientes</p>
        <p>
            @Html.ActionLink("VER", "SelectCustomer", "Sale", new { id = "" }, new { @class = "btn btn-primary", role = "button" })
        </p>
    </div>
    <div class="col-md-6 text-center">
        <p class="lead">Lista de ventas</p>
        <p>
            @Html.ActionLink("VER", "SelectSale", "Sale", new { id = "" }, new { @class = "btn btn-primary", role = "button" })
        </p>
    </div>
    <div class="col-md-6 text-center">
        <p class="lead">Ingresar Venta</p>
        <p>
            @Html.ActionLink("VER", "CreateSale", "Sale", new { id = "" }, new { @class = "btn btn-primary", role = "button" })
        </p>
    </div>
    <div class="col-md-6 text-center">
        <p class="lead">Agregar Venta cliente nuevo</p>
        <p>
            @Html.ActionLink("VER", "CreateSaleCustomer", "Sale", new { id = "" }, new { @class = "btn btn-primary", role = "button" })
        </p>
    </div>
</div>

Seguros.Falabella.Application/Views/Sale/SelectCustomer.cshtml
@model IEnumerable<Seguros.Falabella.Application.ServiceSale.Customer>

@{
    ViewBag.Title = "SelectCustomer";
}

<h2>Lista Clientes</h2>

<table class="table">
    <tr>
        
        <th>
            @Html.DisplayNameFor(model => model.cust_cc)
        </th>        
        <th>
            @Html.DisplayNameFor(model => model.cust_name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.cust_city)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.cust_dateOfBirth)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.cust_address)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.cust_lastName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.cust_phone)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.cust_cc)
        </td>        
        <td>
            @Html.DisplayFor(modelItem => item.cust_lastName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.cust_name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.cust_city)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.cust_dateOfBirth)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.cust_address)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.cust_phone)
        </td>
    </tr>
}

</table>
<p>
    @Html.ActionLink("Back to List", "Index")
</p>

Seguros.Falabella.Application/Views/Sale/SelectSale.cshtml
@model IEnumerable<Seguros.Falabella.Application.ServiceSale.Sale>

@{
    ViewBag.Title = "SelectSale";
}

<h2>Lista venta</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.cust_cc)
        </th>        
        <th>
            @Html.DisplayNameFor(model => model.cust_lastName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.cust_name)
        </th>        
        <th>
            @Html.DisplayNameFor(model => model.sale_assistance)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.sale_coverage)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.sale_prima)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.prod_name)
        </th>
        <th>Detalle</th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.cust_cc)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.cust_lastName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.cust_name)
        </td>        
        <td>
            @Html.DisplayFor(modelItem => item.sale_assistance)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.sale_coverage)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.sale_prima)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.prod_name)
        </td>
        <td>
            @Html.ActionLink("Ver", "SelectSaleId", new {  id=item.sale_id })
        </td>
    </tr>
}

</table>

<p>
    @Html.ActionLink("Back to List", "Index")
</p>

Seguros.Falabella.Application/Views/Sale/SelectSaleId.cshtml
@model Seguros.Falabella.Application.ServiceSale.Sale

@{
    ViewBag.Title = "SelectSaleId";
}

<h2>SelectSaleId</h2>

<div>
    <h4>Sale</h4>
    <hr />
    <dl class="dl-horizontal">        

        <dt>
            @Html.DisplayNameFor(model => model.cust_cc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.cust_cc)
        </dd> 

        <dt>
            @Html.DisplayNameFor(model => model.cust_lastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.cust_lastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.cust_name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.cust_name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.cust_city)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.cust_city)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.cust_dateOfBirth)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.cust_dateOfBirth)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.cust_address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.cust_address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.cust_phone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.cust_phone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.prod_code)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.prod_code)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.prod_features)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.prod_features)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.prod_name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.prod_name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.sale_assistance)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.sale_assistance)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.sale_coverage)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.sale_coverage)
        </dd>        

        <dt>
            @Html.DisplayNameFor(model => model.sale_prima)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.sale_prima)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Back to List", "SelectSale")
</p>